# Generated by Django 4.0.4 on 2022-06-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_status_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('bucketName', models.CharField(max_length=100)),
            ],
        ),
    ]
