# Generated by Django 4.0.4 on 2022-05-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clouduser', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cloudyuser',
            new_name='Clouduser',
        ),
    ]
