# Generated by Django 4.0.4 on 2022-06-02 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='fileName',
            field=models.CharField(default='20220602160222', max_length=100),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folderName',
            field=models.CharField(default='20220602160222', max_length=100),
        ),
    ]
