# Generated by Django 4.0.4 on 2022-05-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devbox', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
