# Generated by Django 4.0.4 on 2022-05-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devbox', '0003_folder_uuid_alter_files_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='fileName',
            field=models.CharField(default='20220520063643', max_length=100),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folderName',
            field=models.CharField(default='20220520063643', max_length=100),
        ),
    ]
