# Generated by Django 4.0.4 on 2022-05-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devbox', '0003_alter_files_filename_alter_folder_foldername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='fileName',
            field=models.CharField(default='20220525173155', max_length=100),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folderName',
            field=models.CharField(default='20220525173155', max_length=100),
        ),
        migrations.AlterField(
            model_name='recyclebins',
            name='deletedFileID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_files', to='devbox.files'),
        ),
    ]
