# Generated by Django 4.0.4 on 2022-05-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devbox', '0004_alter_files_filename_alter_folder_foldername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='fileName',
            field=models.CharField(default='20220525201404', max_length=100),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folderName',
            field=models.CharField(default='20220525201404', max_length=100),
        ),
    ]
