# Generated by Django 4.0.4 on 2022-06-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devbox', '0006_alter_files_filename_alter_folder_foldername'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='userName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='userName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='fileName',
            field=models.CharField(default='20220604153612', max_length=100),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folderName',
            field=models.CharField(default='20220604153612', max_length=100),
        ),
    ]
