# Generated by Django 4.0.4 on 2022-05-08 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devbox', '0006_alter_files_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='filename',
        ),
        migrations.AddField(
            model_name='files',
            name='fileName',
            field=models.CharField(default=datetime.datetime(2022, 5, 8, 5, 25, 55, 812211, tzinfo=utc), max_length=100),
        ),
    ]
